# Generated by Django 2.2.13 on 2020-10-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0058_auto_20201023_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='left',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='node',
            name='right',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
